# Generated by Django 2.2.12 on 2020-12-01 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False, help_text='Display the video on the home page.')),
                ('disable', models.BooleanField(default=False, help_text='Hide the video from all pages.')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('youtube_id', models.CharField(help_text='The YouTube ID of the video, e.g:uQhTuRlWMxw for the video at https://www.youtube.com/watch?v=uQhTuRlWMxw', max_length=30)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
