# Generated by Django 3.2.9 on 2021-11-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-date', '-id')},
        ),
    ]
