# Generated by Django 2.2.12 on 2020-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='disable',
            field=models.BooleanField(default=False, help_text='Hide the article from all pages.'),
        ),
        migrations.AlterField(
            model_name='news',
            name='display',
            field=models.BooleanField(default=False, help_text='Display the article on the home page.'),
        ),
    ]
