# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('package', models.CharField(max_length=50)),
                ('version_str', models.CharField(max_length=20, verbose_name=b'Version (String)')),
                ('version_int', models.IntegerField(verbose_name=b'Version (Integer)')),
                ('download_url', models.CharField(max_length=150, verbose_name=b'Download URL')),
            ],
            options={
                'ordering': ('version_int',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('active', 'package')]),
        ),
    ]
