# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-18 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='download_url',
            field=models.CharField(max_length=150, verbose_name='Download URL'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_int',
            field=models.IntegerField(verbose_name='Version (Integer)'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_str',
            field=models.CharField(max_length=20, verbose_name='Version (String)'),
        ),
    ]
