# Generated by Django 5.2.1 on 2025-05-22 16:40

import versions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0002_auto_20190718_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='auto_update_url',
            field=models.JSONField(default=versions.models.default_auto_update_url),
        ),
    ]
