# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20190718_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='pre_release',
            field=models.BooleanField(default=False),
        ),
    ]
