# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-22 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0005_version_pre_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='released',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
