# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-23 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0006_auto_20190722_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('package__order', 'pre_release', '-released', 'name')},
        ),
        migrations.AddField(
            model_name='version',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
