# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-24 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0008_auto_20190723_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='epub_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='version',
            name='pdf_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='version',
            name='tarball_doc',
            field=models.BooleanField(default=False),
        ),
    ]
