# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-24 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0009_auto_20190724_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
