# Generated by Django 3.2.15 on 2022-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0010_auto_20190724_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together={('package', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('distribution', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('package', 'name')},
        ),
    ]
