# Generated by Django 5.2.1 on 2025-05-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0011_auto_20221128_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.version'),
        ),
    ]
