# Generated by Django 2.2.12 on 2021-10-26 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False, help_text='Display the blog on the home page.')),
                ('disable', models.BooleanField(default=False, help_text='Hide the blog from all pages.')),
                ('date', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('url', models.CharField(help_text='The URL of the blog', max_length=250)),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
    ]
