# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tsvector_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('download', '0004_auto_20190718_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(help_text='The file name of the page', max_length=100)),
                ('title', models.CharField(help_text='The title of the page', max_length=500)),
                ('header', models.TextField(blank=True, help_text='The header tabs for the page.')),
                ('body', models.TextField(blank=True, help_text='The body of the page.')),
                ('search', tsvector_field.SearchVectorField(blank=True, columns=[tsvector_field.WeightedColumn('title', 'A'), tsvector_field.WeightedColumn('body', 'D')], language='english')),
                ('version', models.ForeignKey(help_text='Select the Product Version to which this page applies.', on_delete=django.db.models.deletion.CASCADE, to='download.Version')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('version', 'file')]),
        ),
    ]
