# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-19 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('version', 'title')},
        ),
        migrations.AddField(
            model_name='page',
            name='contents',
            field=models.TextField(blank=True, help_text='The contents block of the page.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='header',
            field=models.TextField(blank=True, help_text='The header block for the page.'),
        ),
    ]
